// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Counter, CounterTableId } from "./tables/Counter.sol";
import { Movable, MovableTableId } from "./tables/Movable.sol";
import { Player, PlayerTableId } from "./tables/Player.sol";
import { Position, PositionTableId } from "./tables/Position.sol";
import { MapConfig } from "./tables/MapConfig.sol";
